In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
dataset=pd.read_csv('wpbcrec.csv')
X = dataset.iloc[:, 1:32].values
Y = dataset.iloc[:, 33].values

In [143]:
dataset.head(15)

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0   119513        18.02         27.60          117.50     1013.0   
1     8423        17.99         10.38          122.80     1001.0   
2   842517        21.37         17.44          137.50     1373.0   
3   843483        11.42         20.38           77.58      386.1   
4   843584        20.29         14.34          135.10     1297.0   
5   843786        12.75         15.29           84.60      502.7   
6   844359        18.98         19.61          124.40     1112.0   
7   844582        13.71         20.83           90.20      577.9   
8   844981        13.00         21.82           87.50      519.8   
9   845010        12.46         24.04           83.97      475.9   
10  845636        16.02         23.24          102.70      797.8   
11  846100        15.78         17.89          103.60      781.0   
12  846381        15.85         23.95          103.70      782.7   
13  847990        14.54         27.54           96.73      658.8   
14  848406        14.68         20.13           94.74      684.5   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.09489           0.10360         0.10860              0.07055   
1           0.11840           0.27760         0.30010              0.14710   
2           0.08836           0.11890         0.12550              0.08180   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.11890           0.15690         0.16640              0.07666   
6           0.09087           0.12370         0.12130              0.08910   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.08401           0.10020         0.09938              0.05364   
13          0.11390           0.15950         0.16390              0.07364   
14          0.09867           0.07200         0.07395              0.05259   

    symmetry_mean  ...   smoothness_worst  compactness_worst  concavity_worst  \
0          0.1865  ...             0.1195             0.1926           0.3140   
1          0.2419  ...             0.1622             0.6656           0.7119   
2          0.2333  ...             0.1188             0.3449           0.3414   
3          0.2597  ...             0.2098             0.8663           0.6869   
4          0.1809  ...             0.1374             0.2050           0.4000   
5          0.1995  ...             0.1706             0.4196           0.5999   
6          0.1727  ...             0.1144             0.3371           0.2990   
7          0.2196  ...             0.1654             0.3682           0.2678   
8          0.2350  ...             0.1703             0.5401           0.5390   
9          0.2030  ...             0.1853             1.0580           1.1050   
10         0.1528  ...             0.1181             0.1551           0.1459   
11         0.1842  ...             0.1396             0.5609           0.3965   
12         0.1847  ...             0.1131             0.1924           0.2322   
13         0.2303  ...             0.1678             0.6577           0.7026   
14         0.1586  ...             0.1464             0.1871           0.2914   

    concave points_worst  symmetry_worst  fractal_dimension_worst  Tumor_size  \
0                0.11700          0.2677                  0.08113         5.0   
1                0.26540          0.4601                  0.11890         3.0   
2                0.20320          0.4334                  0.09067         2.5   
3                0.25750          0.6638         

In [99]:
dataset.shape

(198, 35)

In [100]:
dataset.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  1.980000e+02   198.000000     198.00000      198.000000   198.000000   
mean   1.990469e+06    17.412323      22.27601      114.856566   970.040909   
std    2.889025e+06     3.161676       4.29829       21.383402   352.149215   
min    8.423000e+03    10.950000      10.38000       71.900000   361.600000   
25%    8.557452e+05    15.052500      19.41250       98.160000   702.525000   
50%    8.863390e+05    17.290000      21.75000      113.700000   929.100000   
75%    9.279958e+05    19.580000      24.65500      129.650000  1193.500000   
max    9.411300e+06    27.220000      39.28000      182.100000  2250.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       198.000000        198.000000      198.000000           198.000000   
mean          0.102681          0.142648        0.156243             0.086776   
std           0.012522          0.049898        0.070572             0.033877   
min           0.074970          0.046050        0.023980             0.020310   
25%           0.093900          0.110200        0.106850             0.063670   
50%           0.101900          0.131750        0.151350             0.086075   
75%           0.110975          0.172200        0.200500             0.103925   
max           0.144700          0.311400        0.426800             0.201200   

       symmetry_mean     ...       area_worst  smoothness_worst  \
count     198.000000     ...       198.000000        198.000000   
mean        0.192754     ...      1404.958586          0.143921   
std         0.027437     ...       586.006972          0.022004   
min         0.130800     ...       508.100000          0.081910   
25%         0.174075     ...       947.275000          0.129325   
50%         0.189350     ...      1295.000000          0.141850   
75%         0.209325     ...      1694.250000          0.154875   
max         0.304000     ...      3903.000000          0.222600   

       compactness_worst  concavity_worst  concave points_worst  \
count         198.000000       198.000000            198.000000   
mean            0.365102         0.436685              0.178778   
std             0.163965         0.173625              0.045181   
min             0.051310         0.023980              0.028990   
25%             0.248700         0.322150              0.152650   
50%             0.351300         0.402350              0.179250   
75%             0.423675         0.541050              0.207125   
max             1.058000         1.170000              0.290300   

       symmetry_worst  fractal_dimension_worst  Tumor_size  \
count      198.000000               198.000000  198.000000   
mean         0.323404                 0.090828    2.847475   
std          0.075161                 0.021172    1.937964   
min          0.156500                 0.055040    0.400000   
25%          0.275950                 0.076578    1.500000   
50%          0.310300                 0.086890    2.500000   
75%          0.358800                 0.101375    3.500000   
max          0.663800                 0.207500   10.000000   

       Number_of_Lymph_nodes        Time  
count             194.000000  198.000000  
mean                3.211340   46.732323  
std                 5.479276   34.462870  
min                 0.000000    1.000000  
25%                 0.000000   14.000000  
50%                 1.000000   39.500000  
75%                 4.000000   72.750000  
max                27.000000  125.000000  

[8 rows x 34 columns]

In [101]:
dataset.isnull().sum()
dataset.isna().sum()

id                         0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
Tumor_size                 0
Number_of_Lymph_nodes      4
Outcome                    0
Time          

In [102]:
data=dataset.drop(['id','Outcome'],axis=1)

In [103]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [104]:
import sys
from impyute.imputation.cs import fast_knn
sys.setrecursionlimit(100000)
imputed1=fast_knn(data.values,k=19)
Number_of_Lymph_nodes=imputed1[:,31]

In [105]:
Number_of_Lymph_nodes

array([ 5.        ,  2.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  3.75117638, 10.        ,  1.        , 20.        ,
        0.        ,  0.        ,  0.        ,  6.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        0.        , 13.        ,  0.        ,  0.        ,  2.        ,
        1.        ,  0.        ,  0.        ,  1.39273018, 13.        ,
       10.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
       13.        ,  6.        ,  0.        ,  1.        ,  0.        ,
        4.        ,  2.        ,  0.        ,  1.        ,  0.        ,
        2.        ,  1.        ,  0.        ,  0.        ,  4.        ,
        2.        ,  1.        , 17.        ,  0.        , 15.        ,
       11.        ,  0.        ,  9.        ,  0.        ,  8.        ,
        1.        ,  0.        ,  7.        ,  2.        ,  0.  

In [106]:
Number_of_Lymph_nodes=[ 0 if Number_of_Lymph_nodes1<0 else math.ceil(Number_of_Lymph_nodes1) for Number_of_Lymph_nodes1 in Number_of_Lymph_nodes  ]

In [107]:
Number_of_Lymph_nodes

[5,
 2,
 0,
 0,
 0,
 0,
 4,
 10,
 1,
 20,
 0,
 0,
 0,
 6,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 13,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 13,
 10,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 13,
 6,
 0,
 1,
 0,
 4,
 2,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 4,
 2,
 1,
 17,
 0,
 15,
 11,
 0,
 9,
 0,
 8,
 1,
 0,
 7,
 2,
 0,
 3,
 1,
 2,
 1,
 1,
 4,
 7,
 1,
 0,
 3,
 0,
 4,
 9,
 0,
 1,
 2,
 14,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 1,
 27,
 5,
 24,
 1,
 0,
 1,
 0,
 7,
 0,
 15,
 0,
 0,
 3,
 1,
 1,
 0,
 6,
 2,
 11,
 0,
 0,
 15,
 0,
 18,
 0,
 11,
 0,
 1,
 2,
 2,
 0,
 0,
 4,
 13,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 13,
 16,
 3,
 13,
 0,
 1,
 27,
 0,
 4,
 0,
 0,
 7,
 0,
 7,
 0,
 0,
 9,
 0,
 2,
 0,
 20,
 0,
 4,
 1,
 8,
 1,
 4,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 9,
 4,
 0,
 2,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 1,
 7,
 2,
 0,
 1,
 21,
 2,
 0,
 0,
 3,
 0]

In [108]:
Y

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(imputed1, Y, test_size = 0.25, random_state = 0)

In [110]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [111]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [112]:
Y_pred = classifier.predict(X_test)

In [113]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [114]:
cm


array([[36,  1],
       [ 8,  5]], dtype=int64)

In [115]:
imputed


array([[ 18.02      ,  27.6       , 117.5       , ...,   5.        ,
          5.        ,  31.        ],
       [ 17.99      ,  10.38      , 122.8       , ...,   3.        ,
          2.        ,  61.        ],
       [ 21.37      ,  17.44      , 137.5       , ...,   2.5       ,
          0.        , 116.        ],
       ...,
       [ 17.17      ,  29.19      , 110.        , ...,   3.7       ,
          0.        ,  12.        ],
       [ 21.42      ,  22.84      , 145.        , ...,   3.        ,
          2.69926678,   3.        ],
       [ 16.7       ,  28.13      , 110.3       , ...,   3.5       ,
          0.        ,   6.        ]])

In [116]:
X

array([[1.802e+01, 2.760e+01, 1.175e+02, ..., 2.677e-01, 8.113e-02,
        5.000e+00],
       [1.799e+01, 1.038e+01, 1.228e+02, ..., 4.601e-01, 1.189e-01,
        3.000e+00],
       [2.137e+01, 1.744e+01, 1.375e+02, ..., 4.334e-01, 9.067e-02,
        2.500e+00],
       ...,
       [1.717e+01, 2.919e+01, 1.100e+02, ..., 3.362e-01, 6.033e-02,
        3.700e+00],
       [2.142e+01, 2.284e+01, 1.450e+02, ..., 2.832e-01, 8.981e-02,
        3.000e+00],
       [1.670e+01, 2.813e+01, 1.103e+02, ..., 3.035e-01, 8.036e-02,
        3.500e+00]])

In [117]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [118]:
Y_pred = classifier.predict(X_test)

In [119]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [120]:
cm

array([[36,  1],
       [ 8,  5]], dtype=int64)

In [121]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [122]:
Y_pred = classifier.predict(X_test)

In [123]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [124]:
cm

array([[34,  3],
       [ 8,  5]], dtype=int64)

In [125]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [126]:
Y_pred = classifier.predict(X_test)

In [127]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [128]:
cm

array([[37,  0],
       [12,  1]], dtype=int64)

In [129]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB(priors=None)

In [130]:
Y_pred = classifier.predict(X_test)

In [131]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [132]:
cm

array([[27, 10],
       [ 5,  8]], dtype=int64)

In [133]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [134]:
Y_pred = classifier.predict(X_test)

In [135]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [136]:
cm

array([[28,  9],
       [ 7,  6]], dtype=int64)

cm

In [137]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [138]:
Y_pred = classifier.predict(X_test)

In [139]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [140]:
cm

array([[37,  0],
       [12,  1]], dtype=int64)

In [141]:
import sys
from impyute.imputation.cs import mice
imputed=mice(data.values)
Number_of_Lymph_nodes=imputed[:,31]

In [142]:
data = data["Number_of_Lymph_nodes"].fillna(value=data["Number_of_Lymph_nodes"].mean())