In [103]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('surv.csv')

X = dataset.iloc[:, 2:14].values
Y = dataset.iloc[:, 14].values

In [104]:
dataset.head()

Patient  ID  age  chemo  hormonal  amputation  histtype  diam  posnodes  \
0    s122  18   43      0         0           1         1    25         0   
1    s123  19   48      0         0           0         1    20         0   
2    s124  20   38      0         0           0         1    15         0   
3    s125  21   50      0         1           0         1    15         1   
4    s126  22   38      0         0           1         1    15         0   

   grade  angioinv  lymphinfil   survival  timerecurrence  eventdeath  
0      2         3           1  14.817248       14.817248           0  
1      3         3           1  14.261465       14.261465           0  
2      2         1           1   6.644764        6.644764           0  
3      2         3           1   7.748118        7.748118           0  
4      2         2           1   6.436687        6.318960           0

In [105]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [106]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [107]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [108]:
Y_pred = classifier.predict(X_test)

In [109]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)

In [110]:
cm

array([[47,  4],
       [ 6, 11]], dtype=int64)

In [111]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [112]:
Y_pred = classifier.predict(X_test)

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)

In [81]:
cm

array([[46,  5],
       [ 9,  8]], dtype=int64)

In [82]:
cm.shape

(2, 2)

In [83]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [84]:
Y_pred = classifier.predict(X_test)

In [85]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [86]:
cm

array([[46,  5],
       [ 7, 10]], dtype=int64)

In [87]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [88]:
Y_pred = classifier.predict(X_test)

In [89]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [90]:
cm

array([[47,  4],
       [ 7, 10]], dtype=int64)

In [91]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB(priors=None)

In [92]:
Y_pred = classifier.predict(X_test)

In [93]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [94]:
cm

array([[46,  5],
       [ 6, 11]], dtype=int64)

In [95]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [96]:
Y_pred = classifier.predict(X_test)

In [97]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [98]:
cm

array([[38, 13],
       [ 4, 13]], dtype=int64)

In [99]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [100]:
Y_pred = classifier.predict(X_test)

In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [102]:
cm

array([[50,  1],
       [ 5, 12]], dtype=int64)